from kivy.metrics import dp


SPACESHIP_WIDTH = dp(40)
SPACESHIP_HEIGHT = dp(40)
SPACESHIP_SPEED = dp(5)

SPACESHIP_MAX_FUEL_100 = 100
SPACESHIP_FUEL_DECREASE = .4
SPACESHIP_FUEL_INCREASE = .7
SPACESHIP_START_LIVES = 3

ENEMY_WIDTH = dp(30)
ENEMY_HEIGHT = dp(30)

ASTEROID_WIDTH = dp(30)
ASTEROID_HEIGHT = dp(30)
ASTEROID_SPEED = dp(2)
ASTEROID_SPEED_PROJECTILE = dp(3)

# Number of WIDTH where Asteroid is not a projectile
ASTEROID_NUMBER_WIDTH_PROJECTILE = 4

ENEMY_MAX_SPEED = 1

FPS = 60
ASTEROID_WAITING_COUNT = FPS * 3
ENEMY_WAITING_COUNT = FPS * 3

# Set those values in auto
# when screen will adapt to device size
#SCREEN_WIDTH = 1299
#SCREEN_HEIGHT = 540

# Start game asteroid and enemies number
START_ENEMIES = 1
START_ASTEROID = 1